[#396] Add ability to select variable duration
excaliburjs/Excalibur pull request #2317
Opened 2022-05-16 23:27 UTC by malitherl

===:clipboard: PR Checklist :clipboard:===

- [ ] :pushpin: issue exists in github for these changes
- [ ] :microscope: existing tests still pass
- [ ] :see_no_evil: code conforms to the [style guide](https://github.com/excaliburjs/Excalibur/blob/main/STYLEGUIDE.md)
- [ ] :triangular_ruler: new tests written and passing / old tests updated with new scenario(s)
- [ ] :page_facing_up: changelog entry added (or not needed)

==================

Closes #396

## Changes:

-This would set a random interval after receiving a range  of numbers

2022-05-18 03:05 UTC, eonarheim requested changes
@malitherl Thank you very much for the contribution!  

I want a couple of changes before accepting:
* Implement a new random interval for each invocation of the timer
* Add the ability to pass a `Random` instance into `TimerOptions`
* Update the tests to test the above

2022-05-27 20:12 UTC, eonarheim commented
@malitherl Let me know if you need any assistance with the requested changes 👍

2022-05-30 20:27 UTC, malitherl commented
> @malitherl Let me know if you need any assistance with the requested changes 👍

Hi there! I have made some changes to allow the user to pass ex.Random into TimerOptions, continue to produce random intervals after reset, but I am having some difficulty with allowing the user to change the interval on reset() and also produce Random intervals

2022-06-01 03:50 UTC, eonarheim commented
Hi @malitherl 

> Hi there! I have made some changes to allow the user to pass ex.Random into TimerOptions, continue to produce random intervals after reset, but I am having some difficulty with allowing the user to change the interval on reset() and also produce Random intervals. Any insight would be incredibly helpful, thank you

Is the issue that upon `reset(<newInterval>)` the random intervals return back to the `orignalInterval + randomRange`? 

If so I think it's because the original `interval` is closed over in this arrow function.

```typescript
this.on(()=> this.interval = interval + this.random.integer(this.randomRange[0], this.randomRange[1]))
//                              ^ JavaScript will hold onto this value from the time the () => {} was created
```

One way around that is to create a new member variable to story the "base interval" set by the constructor or the `reset()`

```typescript
private _baseInterval = 10;
private _generateRandomInterval = () => {
  return this._baseInterval + this.random.integer(this.randomRange[0], this.randomRange[1])
}

//...
// in constructor
this._callbacks = [];
this._baseInterval = this.interval = interval;
if (!!randomRange){
  if(randomRange[0] > randomRange[1]){
    throw new Error('min value must be lower than max value for range');
  }
  //We use the instance of ex.Random to generate the range
  this.random = random ?? new Random();
  this.randomRange = randomRange;

  this.interval = this._generateRandomInterval();
  this.on(() => {
    this.interval = this._generateRandomInterval();
  });
}
```

Then your `reset()` can alter the `this._baseInterval = newInterval;` 

That seems to work 👍 when I gave it a shot

<img width="132" alt="image" src="https://user-images.githubusercontent.com/612071/171323860-ee855c31-a993-4a10-97bc-ab565cd7f9af.png">

2022-06-01 03:56 UTC, eonarheim reviewed
Added some suggestions

2022-06-01 03:56 UTC, eonarheim commented on src/engine/Timer.ts
> +        this.interval = newInterval;
```suggestion
        this.interval = newInterval;
        this._baseInterval = newInterval;
```

2022-06-01 03:58 UTC, eonarheim commented on src/engine/Timer.ts
>      this._callbacks = [];
```suggestion
    this._callbacks = [];
    this._baseInterval = this.interval = interval;
    if (!!randomRange){
      if(randomRange[0] > randomRange[1]){
        throw new Error('min value must be lower than max value for range');
      }
      //We use the instance of ex.Random to generate the range
      this.random = random ?? new Random();
      this.randomRange = randomRange;

      this.interval = this._generateRandomInterval();
      this.on(() => {
        this.interval = this._generateRandomInterval();
      });
    }
```

2022-06-01 03:58 UTC, eonarheim commented on src/engine/Timer.ts
> +  public random: ex.Random;
```suggestion
  public random: ex.Random;
  private _baseInterval = 10;
  private _generateRandomInterval = () => {
    return this._baseInterval + this.random.integer(this.randomRange[0], this.randomRange[1])
  }
```

2022-06-01 04:00 UTC, eonarheim commented on src/engine/Timer.ts
> +    }
```suggestion

```

2022-06-01 04:02 UTC, eonarheim commented on src/engine/Timer.ts
> +    }
This gets simplified and folded into the above suggestion

2022-06-01 04:04 UTC, eonarheim commented on src/engine/Timer.ts
>      this._callbacks = [];
We can take advantage of `this.random = random ?? new Random()` (this means if random is not passed in use a new Random) and the `_generateRandomInterval()` helper to simplify a bit

2022-06-07 19:14 UTC, malitherl commented
Everything is working on my end too, and all tests are passing. Thank you again for the suggestions and help @eonarheim

2022-06-07 22:05 UTC, merged