[#3284] perf: reduce allocations for GraphicsGroup draw calls
excaliburjs/Excalibur pull request #3285
Opened 2024-11-23 20:04 UTC by blakearoberts

===:clipboard: PR Checklist :clipboard:===

- [ ] :pushpin: issue exists in github for these changes
- [ ] :microscope: existing tests still pass
- [ ] :see_no_evil: code conforms to the [style guide](https://github.com/excaliburjs/Excalibur/blob/main/STYLEGUIDE.md)
- [ ] :triangular_ruler: new tests written and passing / old tests updated with new scenario(s)
- [ ] :page_facing_up: changelog entry added (or not needed)

==================

Closes #3284 

## Changes:

- reusing single cumulative bounding box for local bounds calculation of `GraphicsGroup` to reduce per-draw allocations

2024-11-23 22:41 UTC, blakearoberts commented
I pulled this change into the same scene I was working with in #3284, and the heap looks much healthier!

![image](https://github.com/user-attachments/assets/38cbedd9-b367-443e-b25e-da0a66b675f0)

2024-11-23 23:34 UTC, eonarheim requested changes
@blakearoberts This looks great! I love that heap graph

2 asks:
* revert extra whitespace changes in changelog
* fix lint (the linter want's a `const bb`)

2024-11-23 23:34 UTC, eonarheim commented on CHANGELOG.md
> +- Perf improvements to `GraphicsGroup` by reducing per draw allocations in bounds calculations
This is the only change we should keep on the changelog, we should revert the rest

2024-11-29 01:28 UTC, eonarheim approved these changes

2024-11-29 01:29 UTC, merged

2024-11-29 01:29 UTC, eonarheim commented
@blakearoberts Thanks again! this was a great add to excalibur! ❤️